language: cpp
cache:
  - pip
  - ccache
  - yarn
  - npm
sudo: required
dist: trusty

os: linux

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - git
      - python
      - python-pip
      - python2.7-dev
      - python-wheel
      - python3-pip
      - python3-dev
      - python3-wheel
      - clang-format-3.8
      - ccache
      - npm
      - nodejs
  ssh_known_hosts: 52.76.173.135

before_install:
  - if [[ "$JOB" == "check_style" ]]; then sudo ln -s /usr/bin/clang-format-3.8 /usr/bin/clang-format; sudo pip install pre-commit flake8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install brew-pip; fi

script:
  - ./scripts/tests.sh all
