language: cpp

compiler: clang

cache:
  - pip
  - ccache
  - yarn
  - npm
sudo: required
dist: trusty

os: osx
osx_image: xcode7.2

env:
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && JOB=test"

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - gcc-4.8
      - g++-4.8
      - git
      - python
      - python-pip
      - python2.7-dev
      - python-wheel
      - python3-pip
      - python3-dev
      - python3-wheel
      - clang-format-3.8
      - ccache
      - npm
      - nodejs
      - pip
  ssh_known_hosts: 13.229.163.131

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install brew-pip; fi

script:
  - if [[ "$JOB" == "test" ]]; then ./scripts/tests.sh all; fi

